### ISSUE TITLE
itau update webputty css colors to be complainte with skin.main_color

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#289]
### Expected behaviour
Tell us what should happen

### Actual behaviour

```css
.headlines i.fa-circle{
  color:#F66433
}
.btn.btn-action i,.events-list .bg-data{
  background-color:#F66433;
  color:#fff
}
```
### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test
